"""empty message

Revision ID: 02000d4f9eea
Revises: e96f96cb7d02
Create Date: 2023-04-27 17:17:27.670334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02000d4f9eea'
down_revision = 'e96f96cb7d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.alter_column('about',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
