"""BookVersion.is_active

Revision ID: 03e8384a23e1
Revises: a41f004cad1a
Create Date: 2023-06-12 12:38:03.152423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03e8384a23e1"
down_revision = "a41f004cad1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book_versions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))
        batch_op.drop_column("exported")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book_versions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("exported", sa.BOOLEAN(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
