"""book.about

Revision ID: 254acdcfcc97
Revises: 02f6f2ebad1b
Create Date: 2023-04-24 12:45:18.363151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254acdcfcc97'
down_revision = '02f6f2ebad1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('about')

    # ### end Alembic commands ###
