"""wallet_id length

Revision ID: 2ec60080de3b
Revises: 4ce4bacc7c06
Create Date: 2023-05-05 16:47:55.533205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec60080de3b'
down_revision = '4ce4bacc7c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('wallet_id',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('wallet_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###
