"""plain_text

Revision ID: a9df3da8cd00
Revises: 883298018384
Create Date: 2023-05-23 10:42:06.239982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a9df3da8cd00"
down_revision = "883298018384"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interpretations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plain_text", sa.Text()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interpretations", schema=None) as batch_op:
        batch_op.drop_column("plain_text")

    # ### end Alembic commands ###
