"""score

Revision ID: f104cc0131c5
Revises: ad0ed27f417f
Create Date: 2023-06-13 17:04:08.590895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f104cc0131c5"
down_revision = "ad0ed27f417f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interpretations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("score", sa.Integer(), nullable=True, server_default="0")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("interpretations", schema=None) as batch_op:
        batch_op.drop_column("score")

    # ### end Alembic commands ###
