import {initBooks} from './books';
import {initContributors} from './contributors';
import {initWallet} from './wallet';
import {initQuill} from './initQuill';
import {initQuillValueToInput} from './quillValueToInput';
import {initComments} from './comment';
import {initVote} from './vote';
import {initTheme} from './theme';
import {initApprove} from './approve';
import {initStar} from './star';
import {initMultipleInput} from './multipleInput';
import {initQuillReadOnly} from './initQuillReadOnly';

initQuillReadOnly();
initBooks();
initContributors();
initQuill();
initQuillValueToInput();
initWallet();
initComments();
initVote();
initTheme();
initApprove();
initStar();
initMultipleInput();
